pdf:
  - application/pdf

docx:
  - application/vnd.openxmlformats-officedocument.wordprocessingml.document

xlsx:
  - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

png:
  - image/png

jpg:
  - image/jpeg

jpeg:
  - image/jpeg

tiff:
  - image/tiff

bmp:
  - image/bmp
